### PR TITLE
Fix docs warnings

### PR DESCRIPTION
**Pull request by thepabloaguilar**
# Fix docs warnings

After the merge of #614 the RTD build failed, unfortunately the build environment differences has contributed to this!!

Changes:

#### Why?

RTD build has 3 steps install.
 1. Upgrade `pip`
2. Install its basic setup:
```text
Pygments==2.3.1 setuptools==41.0.1  mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<1.1
```
3. Install our `requirements` file 

Because the installation of `Pygments==2.3.1` in the second step we've got the following error:
```text
/home/docs/checkouts/readthedocs.org/user_builds/returns/checkouts/latest/docs/pages/contrib/mypy_plugins.rst:42: WARNING: Pygments lexer name 'toml' is not known
```
The `toml` lexer was added in `2.4.0` pygments version

___P.S.:___: `Sphinx` has the `pygments` dependency too, but its constraint does not subscribe the old version because it's `Pugments>2.0`

### Resolves `autofunction` error in `pointfree.rst`

It's just a minor mistake that generates the following error:
```text
WARNING: autodoc: failed to import function 'bind_optional.bind_optional' from module 'returns.pointfree'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/returns/envs/latest/lib/python3.7/site-packages/sphinx/util/inspect.py", line 324, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: 'function' object has no attribute 'bind_optional'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/returns/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_object
    obj = attrgetter(obj, attrname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/returns/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 246, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/returns/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 2078, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/returns/envs/latest/lib/python3.7/site-packages/sphinx/util/inspect.py", line 340, in safe_getattr
    raise AttributeError(name)
AttributeError: bind_optional
```
I just changed from:
```rst
.. autofunction:: returns.pointfree.bind_optional.bind_optional
```
to:
```rst
.. autofunction:: returns.pointfree.bind_optional
```

### Creates sphinx plugin

I've created a simple `sphinx` plugin to add a blank line after the content processed by `sphinx_autodoc_typehints`.
With that we do not have more warnings!

## Checklist

- [X] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)

## Related issues

Refs #568

### CODE REVIEW

File: returns/contrib/sphinx_autodoc_typehints.py [hunk 1]
```diff
@@ -0,0 +1,459 @@
...
+        if lines[-1]:
+            lines.append('')
+
+
+def builder_ready(app):
+    if app.config.set_type_checking_flag:
+        typing.TYPE_CHECKING = True
+
+
+def setup(app):
```
Comment (sobolevn) [inline returns/contrib/sphinx_autodoc_typehints.py:451]: Let's better turn off this `fail_on_warnings` thing! This looks scary!
I don't want to vendor this much code 😞

Comment (thepabloaguilar) [reply returns/contrib/sphinx_autodoc_typehints.py:451]: Good news, I realized we can do this (fix the warnings) inside our `conf.py` file!! I'll code asap to update this PR

Comment (thepabloaguilar) [reply returns/contrib/sphinx_autodoc_typehints.py:451]: I've created a very minimal plugin to deal with it

**Comment by thepabloaguilar** [comment]
We don't need to package the plugin with `returns`, we can just put the script under the `docs` folder to be happy!

**Comment by thepabloaguilar** [comment]
@sobolevn I think everything is good now!!

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
@thepabloaguilar what needs to be done to RTD to our CI?

**Comment by thepabloaguilar** [comment]
After this PR the RTD build should works, so we just need to enable the RTD check #547. Btw, just you can do it!

**Comment by thepabloaguilar** [comment]
@sobolevn I've merged here and everything worked correctly. The build has passed!!
